### ISSUE TITLE
 [ sometimes ignored

### ISSUE THREAD

**Issue by EtherFrog** [tomsmeding/MarioLANG#2]
In some cases  [ don't ignore the next instruction even if it should 
examples:

```
+     
+ "====[
+ >    :
       [
  ! - :<
==#=====
```
output
`3322110` instead of `332211`

and

```
+++         <first part
====== 
 ![ - <
 #===="
:>    !
:"====#
:
>
+++         <second part
====== 
 >[ - <
  ===="
:     !
:=====#
:
!
=

```

go into an infite lopp during the second part because the program don't ignore the `>` even at 0

**Comment by tomsmeding** [comment]
Thanks for reporting! Please note that this code is old, so I'm not surprised that it contains bugs...
I believe I've fixed this one with the commit below, please test!

**Comment by pavelbraginskiy** [comment]
By the way, you might be unaware of this, but there's a MarioLANG online interpreter that uses your implementation at [tryitonline.net](https://tio.run/##jZA7CsMwDEB3nUK2FwljSIcuTaSLZMpUCv1A7w@uYtqYQlP7LRoEjyfdluflcV3u55xHHgk1MUeORDSBrHj5AGiom8vkIN8LBsU/aCKKzBNU3w/8JtQ57ZioFPC@JGxZxNjAsqwq2rFI0sJXsbbEa@SJW8ZQX@iwh9JrsSg9lGBwRD1qKw5d1nc15Hwc8DC8AA).

**Comment by tomsmeding** [comment]
@pavelbraginskiy Thanks! I was indeed not aware, and only now remembered that this thing is actually mentioned on esolangs.org. Good that there are people looking for bugs, then, I suppose. :)
